# Site wide configuration

title:            Dal4Segno's Whatnot
locale:           ko_KR
url: https://dal4segno.github.io
timezone: "Asia/Seoul"

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
categories:
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Dal4Segno
  avatar: ruby-warrior.png
  bio: "이것저것 마음가는데로"
  email: "dal4segno@gmail.com"
  disqus-shortname: dal4segno
  twitter: #username
  facebook: "dongseoblee.52"
  google:
    plus: #username
    analytics: "UA-45713206-2"
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: dal4segno
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username


  
include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
