# Site settings
title: Dal4Segno's Whatnot. 
email: dal4segno@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Computer, Digital Forensics, etc...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dal4segno.github.io" # the base hostname & protocol for your site
github_username:  dal4segno
facebook: dal4segno@gmail.com

# Build settings
markdown: redcarpet
comments:
  provider: disqus
  disqus:
    short_name: dal4segno

assests:
  sources:
    - _assets/fonts

paginate: 3
paginate_path: "blog/page:num"
